server:
  port: 8080

spring:
  application:
    name: chat-manager

eureka:
  client:
    service-url:
      defaultZone: 92.63.103.228:8761/eureka/
      
com:
  chat-manager:
    telegram:
      token: 6198426623:AAFfZkS4SY1GiJIbWoW5_zTQNyZ9jpSIMfQ
      username: OpenAdminChatBot      
