server:
  port: 8080

spring:
  application:
    name: chat-manager-notification-service
  r2dbc:
    url: r2dbc:postgresql://localhost/postgres
    username: postgres
    password: postgres 

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
