server:
  port: 8080

spring:
  application:
    name: chat-manager-notification-service
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:5433/postgres
    username: postgres
    password: docker
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    url: jdbc:postgresql://${DB_HOST:localhost}:5433/postgres
    user: postgres
    password: docker

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
