server:
  port: 8081

spring:
  application:
    name: chat-manager

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
com:
  chat-manager:
    notification:
      url: http://localhost:8080
    telegram:
      token: 6198426623:AAFfZkS4SY1GiJIbWoW5_zTQNyZ9jpSIMfQ
      username: OpenAdminChatBot
